/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Emergencies: typeof import('./components/Emergencies.vue')['default']
    Emergencies2: typeof import('./components/Emergencies2.vue')['default']
    Emergencies3: typeof import('./components/Emergencies3.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
